### ISSUE TITLE
README has out of date information on adding the plugin

### ISSUE THREAD

**Issue by violuke** [eclipsesource/tabris-plugin-barcode-scanner#12]
Following a [discussion on Slack](https://tabrisjs.slack.com/archives/C0AQ5BK36/p1582140989047900) we realised that the install instructions are out of date.

The instructions suggest adding the following to `config.xml`:
```xml
<plugin name="tabris-plugin-barcode-scanner" spec="1.x" />
```

But for compatibility with the latest versions of Tabris you need
```xml
<plugin name="tabris-plugin-barcode-scanner" spec="3.x" />
```

**Comment by mpost** [comment]
Thanks for the heads up. The README has been updated in https://github.com/eclipsesource/tabris-plugin-barcode-scanner/commit/d6268f327abd43dc796b87b7890a1a00c63b7afc.
