### ISSUE TITLE
Detect event is triggered multiple times after first

### ISSUE THREAD

**Issue by josiahking** [eclipsesource/tabris-plugin-barcode-scanner#14]
### Problem description

Continuous use of the plugins makes the detect duplicate data or get triggered multiple times.
When I scan a qr code, and detection occurred, I stop the scanner and get the data.
Starting the scanner again to scan code, on detect, the scanner stops but then the detect event is trigger twice now and more times depending on the previous trigger count.
The makes the code inside the detection event to run multiple times.

### Expected behavior

Expect the detect event to be just ones
### Environment

- Tabris.js version: 3.5 
- Device: Samsung
- OS: Android 6

### Code snippet

```javascript
// A minimal, *self-contained* code snippet to reproduce the problem:
scanner.on('detect', (e) => {
    indicator.visible = true;
	processingCapture = true;
	//console.log(`Detected ${e.format} code with data ${e.data}`)
	scanner.stop();
	//processCapture(e.data,accessData);
  }).on('error', (e) => console.log(e.error));
```

**Comment by elshadsm** [comment]
@josiahking, thank you for reporting the issue, but I couldn't reproduce it with the provided code part. It would be better if you provided a complete snippet that we run it directly. You can also try my snippet below:

```JavaScript
const { Composite, Button, contentView } = require('tabris');

let scanner = new esbarcodescanner.BarcodeScannerView({
  left: 0, top: 0, right: 0, bottom: '#controls',
}).on('detect', (event) => {
  console.log(`Detected ${event.format} code with data ${event.data}`);
  scanner.stop();
}).on('activeChanged', ({ value: active }) => {
  scannerButton.text = (active ? 'Stop' : 'Start') + ' barcode scanner';
}).on('error', (event) => console.error(event.error))
  .appendTo(contentView);

let controls = new Composite({
  id: 'controls',
  left: 0, right: 0, bottom: 0,
  background: '#FAFAFA',
}).appendTo(contentView);

let scannerButton = new Button({
  left: 16, right: 16, bottom: 24
}).onSelect(() => toggleScanner())
  .appendTo(controls);

function toggleScanner() {
  if (scanner.active) {
    scanner.stop();
  } else {
    scanner.start(['qr']);
  }
}

toggleScanner();
```

**P.S.**

**I would suggest using the plugin with the Tabris 3.6 version.**

**Comment by josiahking** [comment]
Hi @elshadsm here is the code that I experienced this issue on

```
let tabFolder = new TabFolder({
  left: 0, top: 0, right: 0, bottom: 0, tabBarLocation: 'bottom'
})
.onSelect(({selection}) => {
  homePage.title = selection.title;
}).appendTo(contentView);

let scanner = new esbarcodescanner.BarcodeScannerView({
  left: 0, right: 0, top: 0, bottom: 0,
  scaleMode: 'fill'
});

let historyTab = new Tab({
  title: 'History',
  image: 'src/assets/history-red.png'
})
.on('select', () => {
  if(scanner.active == true){
	scanner.stop();
  }
})
.appendTo(tabFolder);

let scanTab = new Tab({
  title: 'Scan Badge QR',
  image: 'src/assets/scan-red.png'
})
.on('select', (e) => {
  if(scanner.active != true){
      scanner.start(['qr']);
  }
  scanner.on('detect', (e) => {
//change to 'once' after issue
//console.log(`Detected ${e.format} code with data ${e.data}`)
    scanner.stop();
	//processCapture(e.data,accessData);
  }).on('error', (e) => console.log(e.error));
})
.appendTo(tabFolder);
scanner.appendTo(scanTab);
```

**Comment by elshadsm** [comment]
Hi @josiahking. It seems that you are putting this code:
```JavaScript
scanner.on('detect', (e) => {
//change to 'once' after issue
//console.log(`Detected ${e.format} code with data ${e.data}`)
    scanner.stop();
	//processCapture(e.data,accessData);
}).on('error', (e) => console.log(e.error));
```
into the **select** handler of the '**Scan Badge QR**' Tab:
`.on('select', (e) => {...})`

This means that every time you select the '**Scan Badge QR**' Tab, you add a new **detect** event handler to the scanner. As a result, your single **detect** event is handled by multiple handlers.

I suggest moving the **detect** event handler `scanner.on('detect', (e) => {...})` to the `esbarcodescanner.BarcodeScannerView` creation.

**Comment by josiahking** [comment]
Thanks @elshadsm I guess thats where the problem was coming from.
Thanks I really learnt.
