### ISSUE TITLE
scaleMode "fill" does not work

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-plugin-barcode-scanner#6]
### Problem description

Setting the `scaleMode` to `"fill"` does not have any effect. The scanner appears as if it would have been configured with `scaleMode` `"fit"`. This works as expected on Android.

### Expected behavior

`scaleMode` `"fill"` should make the camera frame cover the view bounds as documented, i.e. in the example, no red area should  be visible.

### Environment

- Tabris.js version: 2.4
- Device: iPhone 6
- OS: iOS 11.2.5

### Code snippet

In the example, replace the `BarcodeScannerView` constructor call with:
```javascript
...
let scanner = new esbarcodescanner.BarcodeScannerView({
  left: 0, top: 0, width: 200, height: 200,
  background: 'red',
  scaleMode: 'fill'
}).on('detect', (event) => {
...
```

**Comment by patrykmol** [comment]
Fixed in https://github.com/eclipsesource/tabris-plugin-barcode-scanner/commit/ac5dd074f8f9b7156f68a90f9c125e0294a1cd22.
