### ISSUE TITLE
Plugin does not work on some devices

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-plugin-barcode-scanner#7]
### Problem description

When using Galaxy J3 (2016), no barcodes can be successfully detected.

### Expected behavior

The barcode scanner should work for all devices running a supported Android version.

### Environment

- Tabris.js version: 2.4
- Device: Samsung Galaxy J3 (2016)
- OS: Android 5.1.1

### Code snippet

Reproducible in the plugin example.

**Comment by mpost** [comment]
The Google Vision API used in the Android implementation of the plugin downloads native binaries when an app using the vision api is installed or first launched. Usually the download happened before first launch when but if the device is out of storage the binaries can not be downloaded. This was very likely the case here.

We will fire an error message noting that the vision system is not ready.

**Comment by mpost** [comment]
The proposed message is fired when the device is not ready. Closing as resolved.
